### ISSUE TITLE
Can we use any other controls instead of pose? 

### ISSUE THREAD

**Issue by i-amgeek** [Wangt-CN/DisCo#1]
Great work @Wangt-CN.  Currently the repo is using 2D keypoints to control the pose of output. Is it possible to replace pose with canny or depth based control? If yes, would it require only replacing controlnet model or retraining complete model? Thanks.

**Comment by Wangt-CN** [comment]
Hi @i-amgeek, thanks for your interests to our work. 
Answer is "of course" ! 

Firstly, the [pre-train part](https://github.com/Wangt-CN/DisCo#human-attribute-pre-training-code-coming-soon) does not contain

**Comment by Wangt-CN** [comment]
(Sorry that I accidentally touched "close the issue" by accident.)
Hi @i-amgeek, thanks for your interests to our work.
Answer is "of course" !

Firstly, the [pre-train part](https://github.com/Wangt-CN/DisCo#human-attribute-pre-training-code-coming-soon) does not contain any condition control. Therefore, you can feel free to fine-tuning based on the given [pretrained model](https://storage.googleapis.com/disco-checkpoint-share/checkpoint_pretrain/0.7m_pretrain/mp_rank_00_model_states.pt).

Secondly, for the fine-tuning, you can check our existing successful practice with 2d pose to design another condition. In general, it could be work to just replace the pose controlnet path with another condition such as canny. I did not try this before, but I believe this is a great idea.

Feel free to further comment here for more discussions.
Best,
Tan

**Comment by Wangt-CN** [comment]
Just close this issue. Feel free to re-open the issue for any further problems.
