### ISSUE TITLE
support multi-gpus

### ISSUE THREAD

**Issue by NguyenTriTrinh** [Wangt-CN/DisCo#10]
hi,  I've tried running the code on multiple GPUs, but it seems that it doesn't utilize all available GPU resources. Could you please provide some guidance on how I can modify the code or which commands I should use to enable multi-GPU support?  Thank you very much for your help.

**Comment by Wangt-CN** [comment]
Hi, thanks for your interests! 
You do not need to modify any code. Could you please try adding `mpirun -np {GPU NUM}` in the running command?
For example, `AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 mpirun -np 8 python finetune_sdm_yaml.py xxx`. I have also updated the readme under [this section](https://github.com/Wangt-CN/DisCo#2-wo-classifier-free-guidance-cfg).

**Comment by NguyenTriTrinh** [comment]
Thank you for your prompt response. However, I am still encountering some issues(sorry i am not familiar with DDP). When i try to run `AZFUSE_USE_FUSE=0 QD_USE_LINEIDX_8B=0 NCCL_ASYNC_ERROR_HANDLING=0 mpirun -np 2 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet_attr_pretraining/coco_S256_xformers_tsv_strongrand.py \
--do_train --root_dir /home/zy/.cache/huggingface/hub/ --local_train_batch_size 64 --local_eval_batch_size 64 --log_dir exp/deepfashion \
--epochs 40 --deepspeed --eval_step 2000 --save_step 2000 --gradient_accumulate_steps 1 --learning_rate 1e-3 --fix_dist_seed --loss_target noise --train_yaml ./yaml/train_TiktokDance-coco-single_person-Lindsey_0411_youtube-SHHQ-1.0-deepfashion2-laion_human-masks-single_cap.yaml --val_yaml ./yaml/val_TiktokDance-coco-single_person-SHHQ-1.0-masks-single_cap.yaml --unet_unfreeze_type transblocks --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --max_eval_samples 2000 --strong_aug_stage1 --node_split_sampler 0 ` 
I got the message
```
RuntimeError: The server socket has failed to listen on any local network
address. The server socket has failed to bind to [::]:12475 (errno: 98 - Address
already in use). The server socket has failed to bind to 0.0.0.0:12475 (errno:
98 - Address already in use)
```
But the program can also run with a single GPU. Can you give me some tips to fix that ? thx

**Comment by Wangt-CN** [comment]
Hi @NguyenTriTrinh, this is because that you have launched another process of this code in the same machine. 2 quick solutions:
1. If other process is not important, you can just kill it. Then you can run this one.
2. You can change the the `master_port` in `dist.py` file (https://github.com/Wangt-CN/DisCo/blob/main/utils/dist.py#L24, https://github.com/Wangt-CN/DisCo/blob/main/utils/dist.py#L84) to another one, then you can run the code without this error.

**Comment by NguyenTriTrinh** [comment]
Hi @Wangt-CN , the error shown in the above message can be solved by the solutions you mentioned !  Actually, if I change the `mpirun -np 2 ` to `mpirun -np 1`, the code can run without that error. However, if I set 'np' as 2, the error occurs. Anyway, the code runs with only a single GPU.

**Comment by Wangt-CN** [comment]
Hi, Glad to hear you have resolved the issue. This is because `mpirun -np 1` actually not use the pytorch distribution tool.
