### ISSUE TITLE
'GIT/{:05d}/labels/{:04d}.txt' How to get this file？

### ISSUE THREAD

**Issue by hanhan0521** [Wangt-CN/DisCo#14]
Hello author, I would like to ask, how to get the “self.anno_path = 'GIT/{:05d}/labels/{:04d}.txt'”  of images in the tiktok dataset

        if 'youtube' in anno_pose_path:
            img_key = self.anno_list[idx % self.num_images]
        else:
            anno = list(open(anno_path))
            img_key = json.loads(anno[0].strip())['image_key']
        """
        example:
        {"num_region": 6, "image_key": "TiktokDance_00001_0002.png", "image_split": "00001", "image_read_error": false}
        {"box_id": 0, "class_name": "aerosol_can", "norm_bbox": [0.5, 0.5, 1.0, 1.0], "conf": 0.0, "region_caption": "a woman with an orange dress with butterflies on her shirt.", "caption_conf": 0.9404542168542169}
        {"box_id": 1, "class_name": "person", "norm_bbox": [0.46692365407943726, 0.4977584183216095, 0.9338473081588745, 0.995516836643219], "conf": 0.912740170955658, "region_caption": "a woman with an orange dress with butterflies on her shirt.", "caption_conf": 0.9404542168542169}
        {"box_id": 2, "class_name": "butterfly", "norm_bbox": [0.2368704378604889, 0.5088028907775879, 0.1444256454706192, 0.04199704900383949], "conf": 0.8738771677017212, "region_caption": "a brown butterfly sitting on an orange background.", "caption_conf": 0.9297735554473283}
        {"box_id": 3, "class_name": "butterfly", "norm_bbox": [0.6688584089279175, 0.5137135982513428, 0.11311062425374985, 0.05455022677779198], "conf": 0.8287128806114197, "region_caption": "a brown butterfly sitting on an orange wall.", "caption_conf": 0.9264783379302365}
        {"box_id": 4, "class_name": "blouse", "norm_bbox": [0.4692786931991577, 0.6465241312980652, 0.9283269643783569, 0.6027728319168091], "conf": 0.6851752400398254, "region_caption": "a woman wearing an orange shirt with butterflies on it.", "caption_conf": 0.9978814544264754}
        {"box_id": 5, "class_name": "short_pants", "norm_bbox": [0.44008955359458923, 0.8769687414169312, 0.8799525499343872, 0.2431662678718567], "conf": 0.6741859316825867, "region_caption": "a person wearing an orange shirt and grey sweatpants.", "caption_conf": 0.9731313580907464}
        """

**Comment by Wangt-CN** [comment]
Hi @hanhan0521 , may I ask which config file do you use? Since with current tsv data file, you do not need to use the `anno_list` for Tiktok fine-tuning.

**Comment by hanhan0521** [comment]
Hello author, I have solved this problem and found that it exists in the train_captition.tsv file.
I now have another question, which is how do I pre-train my own dataset。I also got the preprocessed output from Openpose。
How to set the following path？Thank you！！！！！！

self.total_num_videos = 340
        self.anno_path = 'GIT/{:05d}/labels/{:04d}.txt'
        self.image_path = '{:05d}/images/{:04d}.png'
        self.anno_pose_path = '{:05d}/openpose_json/{:04d}.png.json'
        self.ref_mask_path = '{:05d}/masks/{:04d}.png'

        self.image_path_web = '{}/{}'
        self.ref_image_path_web = '{}/{}'
        self.anno_pose_path_web = '{}/openpose_json/{}.json'
        self.ref_mask_path_web = '{}/groundsam/{}.mask.jpg'

        self.image_paths_list = []
        self.ref_image_paths_list = []
        self.ref_pose_paths_list = []
        self.anno_list = []
        self.anno_pose_list = []
        self.anno_init_pose_list = []
        self.mask_list = []

        ft_video_idx = getattr(args, 'ft_idx', '001_1.57_2.17_1x1') # default elon
        if split == 'train': # for training video
            # video_idx = ['001_1.57_2.17_1x1'] # elon mask 2
            # video_idx = ['007_7.36_7.44_1x1'] # 007
            # video_idx = ['001_1.57_2.17_9x16', '001_11.46_11.54_9x16', '001_5.37_5.44_9x16', '001_8.14_8.27_9x16']  # elon mask 1+2+3+4
            video_idx = [ft_video_idx] # 007
            dataset_prefix = self.args.web_data_root
        else: # for pose video
            video_idx = [335, 137]
            # ref_video_idx = '001_1.57_2.17_1x1' # 007
            # ref_video_idx = '007_7.36_7.44_1x1' # 007
            ref_video_idx = ft_video_idx # 007
            dataset_prefix = self.args.tiktok_data_root

**Comment by Wangt-CN** [comment]
Hi @hanhan0521 , for the pre-training, actually you do not need the pose. If you want to pretrain on your own data and do not want to use the tsv format, you may need to revise the dataloader code for the pre-training to use the raw image/mask data. You can refer to this file (https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_mask.py). But note that this file is for fine-tuning, therefore it still consists pose that is no use in pretrain.

**Comment by quqixun** [comment]
I met the same error
```bash
FileNotFoundError: [Errno 2] No such file or directory: './TikTok_dataset/GIT/00137/labels/0262.txt'
```

when I tried to run the command (shown as in [Human-Specific Fine-tuning](https://github.com/Wangt-CN/DisCo#human-specific-fine-tuning) section) with my own settings:
```bash
AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 CUDA_VISIBLE_DEVICES=0 \
python finetune_sdm_yaml.py                                          \
    --cf                        ./config/ref_attn_clip_combine_controlnet_imgspecific_ft/webtan_S256L16_xformers_upsquare.py \
    --pretrained_model          ./ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt \
    --root_dir                  ./run_test                   \
    --ft_idx                    ./finetune_data/001          \
    --log_dir                   ./exp/human_specific_ft_001/ \
    --do_train                                               \
    --local_train_batch_size    32                           \
    --local_eval_batch_size     32                           \
    --epochs                    20                           \
    --deepspeed                                              \
    --eval_step                 500                          \
    --save_step                 500                          \
    --gradient_accumulate_steps 1                            \
    --learning_rate             1e-3                         \
    --fix_dist_seed                                          \
    --loss_target               "noise"                      \
    --unet_unfreeze_type        "crossattn"                  \
    --refer_sdvae                                            \
    --ref_null_caption          False                        \
    --combine_clip_local                                     \
    --combine_use_mask                                       \
    --conds                     "poses" "masks"              \
    --freeze_pose               True                         \
    --freeze_background         False                        \
    --ft_iters                  500                          \
    --ft_one_ref_image          False                        \
    --strong_aug_stage1         True                         \
    --strong_rand_stage2        True
```

The file structure of models and specific human dataset is:
```
Disco
├── ft_checkpoint
│   └── moretiktok_nocfg
│       └── mp_rank_00_model_states.pt
├── run_test
│   └── diffusers
│       └── sd-image-variations-diffusers
│           ├── feature_extractor
│           ├── image_encoder
│           ├── safety_checker
│           ├── scheduler
│           ├── unet
│           └── vae
├── finetune_data   # human specific dataset                                                                                                                                                                                           
│   └── 001                                                                                                                                                                                                 
│       ├── grounded_sam   # ---|                                                                                                                                                                        
│       ├── openpose_json  #    |--> get preprocessed data followling steps in                                                                                                                                                   
│       ├── openpose_vis   # ---|    https://github.com/Wangt-CN/DisCo/blob/main/PREPRO.md
│       ├── 0001.png
│       ├── 0002.png
│       └── ......
├── keli
│   └── dataset
│       └── TikTok_dataset                                                                                                                                                                                          
│           ├── 00001                                                                                                                                                                                               
│           │   ├── densepose                                                                                                                                                                                       
│           │   ├── images                                                                                                                                                                                          
│           │   └── masks
│           ├── 00002
│           └── .....
└── .....
```

**How to run human specific fine-tunning with my own dataset ?**
**How to get the _GIT_ directory which can be found in all ./dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg\*.py ?**

**Comment by Wangt-CN** [comment]
Hi @quqixun, Thanks a lot for reporting the confusion.
1. First, please check if the [config file](https://github.com/Wangt-CN/DisCo/blob/main/config/ref_attn_clip_combine_controlnet_imgspecific_ft/webtan_S256L16_xformers_upsquare.py#L11) indicates to use the data python file, e.g., https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py.
2. Actually the data in GIT folder only contains the frame-name and only is used in validation (https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py#L192). For our experiment, we just use [TikTok data](https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py#L117) for validation. I am trying to upload the GIT folder to share on Github. 
3. But actually, GIT file only contains the frame name. Therefore, as a quick work-around, you can just delete the [use of the anno_path and the related variable](https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py#L192). And then revise this [part](https://github.com/Wangt-CN/DisCo/blob/main/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py#L509-L513) to provide a customized frame name.
4. Due to the flexibility of current human-specific ft pipeline, there may be many work-arounds to do this. Sorry for the confusion and I will then write a brief intro for easily adaptation to the user data.

**Comment by hanhan0521** [comment]
Hello author, I would like to use our code to achieve the posture of driving the target character with its own skeletal keypoints. But when I run the "[/dataset/tiktok_controlnet_t2i_imagevar_combine_mask.py]" file, the cond folder I get is the pose of its own dataset, and the gt folder is still the original human image, and it is not driven, why is that?

![image](https://github.com/Wangt-CN/DisCo/assets/95208134/bc8e2e8d-2fb1-4747-86f1-5b850ff55760)
![gt Dance_00001_0001png](https://github.com/Wangt-CN/DisCo/assets/95208134/77a280de-c2cf-472b-b825-e8c4adac9604)
![cond Dance_00001_0001png](https://github.com/Wangt-CN/DisCo/assets/95208134/56bc5718-816c-4335-bd0f-1c6099b4e7ab)

**Comment by Wangt-CN** [comment]
@hanhan0521 Hi, actually I cannot understand you question. But from the code you give, it seemed that you set the `anno_pose_json` to the Tiktok data. This file contains the skeleton annotation human. BTW, what stage are you trying?
