### ISSUE TITLE
where is  python  tool/video/gen_gifs_for_fvd.py？

### ISSUE THREAD

**Issue by zhangtao22** [Wangt-CN/DisCo#18]
In the gen_eval.sh， #  Generate GIFs of 16 frames, 3 fps
# multi process first 
python  tool/video/gen_gifs_for_fvd.py --root_dir. So where is the gen_gifs_for_fvd.py and the folder video?

**Comment by Wangt-CN** [comment]
Hi all, sorry for the confusion. Please check the new commitment for the missing file.
