### ISSUE TITLE
Why does deepspeed is commented in the finetune file?

### ISSUE THREAD

**Issue by SKBL5694** [Wangt-CN/DisCo#19]
Why dose `if args.deepspeed: ...` is commented in finetune_sdm_yaml.py? Is there any bug with that?

**Comment by DisCo-Dance** [comment]
Hi, no worries, there is no bug with that. It is just an old version code.

**Comment by Wangt-CN** [comment]
Hi, no worries, there is no bug with that. It is just an old version code.
