### ISSUE TITLE
Not able to generate results 

### ISSUE THREAD

**Issue by kunalgoyal9** [Wangt-CN/DisCo#2]
Hi, I am running for below configuration but output is not having texture preserved.
<img width="1355" alt="image" src="https://github.com/Wangt-CN/DisCo/assets/21281457/04f8d8ce-a165-4c18-b7a0-0f174bbf22d9">

**Comment by Wangt-CN** [comment]
Hi @kunalgoyal9 , thanks for your interests to our work.
Although we design a pre-training stage to keep human attributes, current fine-tuning stage only using ~300 human attributes from [TikTok dataset](https://www.yasamin.page/hdnet_tiktok). It is expected that it can not work perfectly for all kinds of human attributes. But it can produce generally good results for such easier clothes. 

You have three options for this problem:
1) You can first check our [pre-trained human attribute model](https://github.com/Wangt-CN/DisCo#human-attribute-pre-training-code-coming-soon) to see if it can generate this kind of clothe. If can, it means that the current pre-training is enough to handle this kind of human attribute.
2) If you have more data for fine-tuning, it will be good to further train our 2nd stage model.
3) You can also try our [3rd stage human-specific fine-tuning](https://github.com/Wangt-CN/DisCo#human-specific-fine-tuning) with your own data. It will greatly improve the model capability for specific human.

**Comment by kunalgoyal9** [comment]
Thanks @Wangt-CN, I surely will check them :)

**Comment by Wangt-CN** [comment]
Moreover, we are trying to further enlarge the pre-training size. Stay tune!
