### ISSUE TITLE
Training/Validation Data Split

### ISSUE THREAD

**Issue by Boese0601** [Wangt-CN/DisCo#27]
Hi, thanks for your great work. I check the TikTok tsv dataset and find that you've already split the dataset into trainig set and validation set. Since it's not easy to match the image with original sequence id of the dataset each by each, Then could you please just clarify that which sequences from original TikTok datset(from 000 to 340) are used for tranining and which are for validation?  Thanks!

**Comment by Boese0601** [comment]
Thanks for your kind reply! That makes things clear. Btw could you please also upload those additional video sequences collected from the internet to Google Drive?

**Comment by Wangt-CN** [comment]
Hi @Boese0601 , I have submitted the query to the corporation to open-source the additional TikTok-style data. Since it is collected by the corporation so we need to get the permission.
Currently, if you want to make a fair comparison, you could follow the penultimate line of Table 1 which does not use the additional data for training.

**Comment by notorious-eric** [comment]
Hi, I download the tsv file and found that there are additional data in the file. Therefore, in the penultimate line of Table 1, you do not use the tsv file you presented, just use 335-340 sequence for evaluation, is that correct?

**Comment by Wangt-CN** [comment]
@notorious-eric Hi, do you mean the evaluation data? All the models are evaluated on the same data, i.e., 10 videos which is the combination of the original testing tiktok and additional data.

**Comment by notorious-eric** [comment]
If I want to make a fair comparison for tiktok tsv, should I chooose 335-340 sequence for evaluation because the additional data is not open-sourced?

**Comment by kelu007** [comment]
> Hi @Boese0601 , thanks for your nice comment.
> 
> For training, we use 000-334 of TikTok dataset; For testing, we find that there are potential risks of the person ID leakage for the TikTok dataset. Therefore, we choose to collect 10 short videos from both the 335-340 sequence and the Internet to make sure there are no person ID coincide for fair comparison.

What are the videos collected from the Internet for evaluation?

**Comment by zhuochen02** [comment]
> 你好@Boese0601，谢谢您的精彩评论。
> 
> 训练时我们使用TikTok的000-334序列；测试时我们发现TikTok数据集存在人物ID泄露的风险，因此我们选择从335-340序列和互联网上分别收集10个短视频，以确保没有人物ID重合，以保证公平的比较。

Why did I download a dataset that didn't have 000 and started with 001

**Comment by zhuochen02** [comment]
> Hi @Boese0601 , thanks for your nice comment.
> 
> For training, we use 000-334 of TikTok dataset; For testing, we find that there are potential risks of the person ID leakage for the TikTok dataset. Therefore, we choose to collect 10 short videos from both the 335-340 sequence and the Internet to make sure there are no person ID coincide for fair comparison.

Why did I download a dataset that didn't have 000 and started with 001
