### ISSUE TITLE
why this effect?

### ISSUE THREAD

**Issue by zzk88862** [Wangt-CN/DisCo#29]
hi，so amazing work
i try this work today，but the effect is so bad，the face is severely deformed，and clothes are also changed
![20230805-131420](https://github.com/Wangt-CN/DisCo/assets/31311358/f3d1c810-6ebe-485a-ae81-66df67233226)

can you tell me how to solve this problem?

**Comment by Wangt-CN** [comment]
Hi, thanks for your interests to our work. Please refer to the issue [here](https://github.com/Wangt-CN/DisCo/issues/2#issuecomment-1605944361).

**Comment by zzk88862** [comment]
@Wangt-CN thanks，
i will try these methods，but I found that the hands in the generated pictures are very distorted. 
Is this a problem with the model?
