### ISSUE TITLE
deploy the model inference locally

### ISSUE THREAD

**Issue by deanSunny** [Wangt-CN/DisCo#3]
Appreciate your great works !@Wangt-CN ，how can I deploy the model inference locally?
Could you please  release the inference code? Thanks a lot :)

**Comment by Wangt-CN** [comment]
Hi @deanSunny, Thanks for your interests to our work! Actually the evaluation code is already invloved in the codebase currently. I will update the evaluation command and the local demo inference jupyter notebook for better reference.

**Comment by Wangt-CN** [comment]
Hi @deanSunny , please check the local inference demo jupyter example code [here](https://github.com/Wangt-CN/DisCo#launch-demo-locally-video-dance-generation-demo-is-on-the-way). Feel free to re-open the issue for any further problems.
