### ISSUE TITLE
About the training data.

### ISSUE THREAD

**Issue by linziqu** [Wangt-CN/DisCo#31]
Thanks for your great work!
I am curious about the Human Attribute Pre-training stage, if you pre-trained the model with the full-body image in SHHQ or just use the cropped upper-body image (e.g. the showed tiktok video results)?

**Comment by Fanghaipeng** [comment]
I have the same question.

**Comment by Wangt-CN** [comment]
Hi @Fanghaipeng @linziqu , sorry for the late responses due to my current limited bandwidth. We just use the original images in the pretraining data, but we include data augmentation in the dataloader with image cropping. So it may result in some half-body images (but not only upper-body images)
