### ISSUE TITLE
About the extra Tiktok-style data

### ISSUE THREAD

**Issue by zehongs** [Wangt-CN/DisCo#34]
Hi @Wangt-CN, thanks for the great work!
I have noticed that you've collected an additional 250 TikTok-style short videos from the internet. Will you consider uploading them?  This would enable us to make a comparison with the the released model trained on it.

**Comment by Wangt-CN** [comment]
Hi @zehongs, I have submitted the query to the corporation to open-source the additional TikTok-style data. Since it is collected by the corporation so we need to get the permission.
