### ISSUE TITLE
如何从你处理好的数据中拿到skeleton中的key points信息？

### ISSUE THREAD

**Issue by Amo5** [Wangt-CN/DisCo#37]
您好，
我想从你处理好的数据中获取skeleton中key points的信息。
我从tsv文件中读取出来pose image的信息后，通过数值分析发现对应位置的像素值和create_custom_dataset_tsvs.py中设置的colors里面rgb对应不上，，看上去好像pose image在存储在tsv中的时候使用的是有损压缩？
期待您的回答，谢谢！

**Comment by Wangt-CN** [comment]
Hi @Amo5 , 我们follow之前的工作，处理好的pose已经是image了，可能不能直接回到key points。如果有需要可以直接用openpose 在image上run一遍得到key points
