### ISSUE TITLE
About openpose and inference code

### ISSUE THREAD

**Issue by anhquannguyen21** [Wangt-CN/DisCo#4]
Thank you for great work @Wangt-CN .
Where is run.py in openpose?
And can you release inference code? so I can run demo on my machine.
Thanks.

**Comment by Wangt-CN** [comment]
Hi @anhquannguyen21, thanks for your interests! I will update the inference demo jupyter and resolve the openpose issue within 2 days.

**Comment by Wangt-CN** [comment]
Hi @anhquannguyen21, please the local inference demo jupyter example code [here](https://github.com/Wangt-CN/DisCo#launch-demo-locally-video-dance-generation-demo-is-on-the-way). The `run.py` file in openpose is also fixed. Feel free to re-open the issue for any further problems.
