### ISSUE TITLE
About the reference image

### ISSUE THREAD

**Issue by zhangtao22** [Wangt-CN/DisCo#40]
what are your criteria about choosing the reference image in 1) Pre-training, 2) General fine-tuning and 3) Human-specific fine-tuning respectively? are they all the first images of a dataset?

**Comment by Wangt-CN** [comment]
Hi @zhangtao22 , for the pre-training, there is no video frame and the reference image is just itself. For fine-tuning and human-specific fine-tuning, the answer is yes.
