### ISSUE TITLE
Human Specific Finetuning

### ISSUE THREAD

**Issue by emcorby2** [Wangt-CN/DisCo#45]
Hi,

Could you please provide some more information about the human specific finetuning model? 

I tried running it and have generated checkpoint files however their dictionary keys are wildly different to the provided checkpoint, 'mp_rank_00_model_states.pt':

My checkpoint: `dict_keys(['models', 'optimizer', 'epoch', 'global_step', 'scheduler'])`

Checkpoint provided: `dict_keys(['module', 'buffer_names', 'optimizer', 'param_shapes', 'lr_scheduler', 'sparse_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'ds_config', 'ds_version'])`

Therefore, when I try to generate new images using my checkpoint it fails at the load_checkpoint_for_deepspeed_diff_gpu function with this message:

`Traceback (most recent call last):
  File "/home/emily/DisCo/VideoGenerationModel/run.py", line 645, in <module>
    trainer.eval_demo_pre()
  File "/home/emily/DisCo/agent.py", line 422, in eval_demo_pre
    self.prepare_dist_model()
  File "/home/emily/DisCo/agent.py", line 199, in prepare_dist_model
    self.load_checkpoint_for_deepspeed_diff_gpu(self.pretrained_model) # load pt model with default pytorch
  File "/home/emily/DisCo/agent.py", line 813, in load_checkpoint_for_deepspeed_diff_gpu
    adaptively_load_state_dict(self.model, checkpoint['module'])
KeyError: 'module'`

I'm not really sure what to do about this issue as it seems the new checkpoints are supposed to be made this way, please advise. Many thanks :)

**Comment by Wangt-CN** [comment]
Hi @emcorby2 , it seems that you can just use the `'module'` in the checkpoint model?
