### ISSUE TITLE
Difficulty finding the inference function

### ISSUE THREAD

**Issue by debjit-bw** [Wangt-CN/DisCo#46]
Hi, @Wangt-CN, first off, great work!!

I want to run inference through code, not gradio. I tried searching for the function to do that, the closest I found is the Agent_LDM. But this takes a reference fg, bg and skeleton. Is there a function which just takes in an image (with a character in it) and a skeleton, and returns the output?

Additionally, any function for end to end video gen?

Thanks

Just another: Will the code be compatible with PyTorch 2?

**Comment by debjit-bw** [comment]
found the solution, closing

**Comment by tbxmh** [comment]
Hi, can you share how you resolved this?

**Comment by seyyedAlirezaGhazanfari** [comment]
> found the solution, closing

please share your solution.
