### ISSUE TITLE
Problem when training with 4090

### ISSUE THREAD

**Issue by volcverse** [Wangt-CN/DisCo#49]
Hi, thanks for the great work. I'm trying to run the training code, but when I do pre_train with multiple 4090 gpus, it always gets stuck and no report is shown. But when training with multiple 3090 and single 4090 everything is fine. I strongly suspect that a deadlock occurs in 4090. I narrow the problem down to `deepspeed.initialize` in agent.py. But I don't know how to solve this problem. 

Any response will be greatly appreciated.

**Comment by Wangt-CN** [comment]
Hi @volcverse , thanks for your interets to our work? I do not have 4090 at hand. All the experiments of DisCo are performed on V100 and A100. I wonder: 1. if you have the exact same package version with the repo? 2. have you tried to upgrade the deepspeed package? 3. I found this issue (https://github.com/microsoft/DeepSpeed/issues/3808) on deepspeed repo but it seemed that is not your case as they do have the error report. Is it normal for the single 4090 gpu?

**Comment by volcverse** [comment]
> Hi @volcverse , thanks for your interets to our work? I do not have 4090 at hand. All the experiments of DisCo are performed on V100 and A100. I wonder: 1. if you have the exact same package version with the repo? 2. have you tried to upgrade the deepspeed package? 3. I found this issue ([microsoft/DeepSpeed#3808](https://github.com/microsoft/DeepSpeed/issues/3808)) on deepspeed repo but it seemed that is not your case as they do have the error report. Is it normal for the single 4090 gpu?

Hi! I found this issue is about p2p of the guy. By setting NCCL_P2P_DISABLE=1 it works. Thanks for your reply!
