### ISSUE TITLE
How should I do inference about Human Attribute Pre-training?

### ISSUE THREAD

**Issue by mingfuyan** [Wangt-CN/DisCo#52]
Hi, thanks for the great work.I want to know how I should do inference, because I want to verify whether my `Human Attribute Pre-training` model is trained well. Can you tell me where the key code is?

Any guidance would be very helpful, thanks!

**Comment by mingfuyan** [comment]
I want to use my own images to validate my model.

**Comment by Wangt-CN** [comment]
Hi @mingfuyan , thanks for your interest. The evaluation of pre-training is similar to the fine-tuning. Therefore, you may check the `visualization` section of [here](https://github.com/Wangt-CN/DisCo#2-wo-classifier-free-guidance-cfg) and [here](https://github.com/Wangt-CN/DisCo#3-w-classifier-free-guidance-cfg-cfg-can-bring-a-slightly-better-results) for reference.
