### ISSUE TITLE
CLIP image encoder receive image size as 224*224

### ISSUE THREAD

**Issue by KenChen701** [Wangt-CN/DisCo#60]
Great and interesting work! The pretrained CLIP image encoder by image variation is for image size 224 * 224. However, the images that you used are 256 * 256. How could you use the pretrained image encoder?

**Comment by RedRAINXXXX** [comment]
The input image will be resized to 224*224 in the dataset. Refer to line 57 of dataset/app_demo_human_image_edit_singleinput.py.

**Comment by Wangt-CN** [comment]
Thanks @RedRAINXXXX !
