### ISSUE TITLE
Cannot download Human_Attribute_Pretrain.tar.gz

### ISSUE THREAD

**Issue by hygenie1228** [Wangt-CN/DisCo#67]
Thanks for sharing interesting work.

I'm currently trying to download the pre-train datasets, following the [instruction](https://github.com/Wangt-CN/DisCo#data-preparation)
I faced an error in the middle of the downloading process.
![image](https://github.com/Wangt-CN/DisCo/assets/69622221/c58c33e0-486b-4cb8-a62c-fccaf93d99c2)

Can you check the integrity of the dataset?
Thank you.

**Comment by Wangt-CN** [comment]
Hi, thanks for your interest. I have just tried to download it (https://drive.google.com/file/d/1N9gioWnkb3ZZytmT3Nzx4VjXjHxLsVB9/view), and it succeeded. Could you please try again?
