### ISSUE TITLE
Question about the CLIP encoder and VAE encoder

### ISSUE THREAD

**Issue by CHNxindong** [Wangt-CN/DisCo#72]
Thanks for your great work. I have one question: 
![image](https://github.com/Wangt-CN/DisCo/assets/20262070/a257be2c-3e1b-4e63-8ace-fc8110b3a5e3)
Why do you use CLIP encoder for foreground encoding but use VAE encoder for background encoding? 

Hope for your response. Thank you! 

Best Wishes

**Comment by Wangt-CN** [comment]
Hi, thanks for your interest in our work. As stated in the paper, this is our specific design. After the experiments, we found that vae encoder can encode as much as possible visual information with large-scale pretraining, thus keep the background well. However, it is not suitable for the human foreground which requires a dynamic interaction with other visual areas.

**Comment by CHNxindong** [comment]
I see. Thanks for your reply!
