### ISSUE TITLE
What is the difference between input image and reference image?

### ISSUE THREAD

**Issue by CHNxindong** [Wangt-CN/DisCo#73]
Thansk for your great work! I have a question about the framework in the paper:
![image](https://github.com/Wangt-CN/DisCo/assets/20262070/56a57a5f-786f-4445-9de9-2c74b7920d64)

What is the meaning of input image? What is the difference between input image and reference image? 

Hope for your reply. Thank you!

**Comment by Wangt-CN** [comment]
Input image is only used in training, which will be added the noise. This is a normal practice of the denoising diffusion model.

**Comment by CHNxindong** [comment]
Is this the DDIM inversion operation?

**Comment by CHNxindong** [comment]
Is this similar to the DDIM inversion?

**Comment by CHNxindong** [comment]
For the better initialization, is it?
