### ISSUE TITLE
how to caculate fvd metrics?

### ISSUE THREAD

**Issue by Allfather9** [Wangt-CN/DisCo#80]
In the context of the paper, was the FVD metric computed for video reconstruction tasks or image animation tasks? Based on the surrounding context, it seems that the FVD metric was evaluated in the context of image animation tasks. My question pertains to the absence of ground truth in image animation tasks. How is the comparison of feature distribution distance between generated and real videos handled in the absence of ground truth? Specifically, if the generated videos are created by driving source frames with a pose sequence, where are the corresponding real videos obtained? Are they directly sourced from the videos corresponding to the source frames?

i saw this code 
`exp_folder=$1
pred_folder="${2:-${exp_folder}/pred_gs3.0_scale-cond1.0-ref1.0}"
gt_folder=${3:-${exp_folder}/gt}`
so what's the gt video?

**Comment by Naive-Bayes** [comment]
Hi, I met the same problem, could you tell me how to get the gt file.

**Comment by yuchenli-sony** [comment]
yeah how to get the gt, gt is means dwpose or origin videos?
