### ISSUE TITLE
the code for computing PSNR is wrong

### ISSUE THREAD

**Issue by Yongssss** [Wangt-CN/DisCo#86]
Your code computing PSNR as follows is wrong:
https://github.com/Wangt-CN/DisCo/blob/8538889c9ee9edd8dd43ffee182d1a91ce7a9828/tool/metrics/ssim_l1_lpips_psnr.py#L13.

The accurate code is mse = np.mean((original/1.0 - compressed/1.0) ** 2), because original and compressed images are uint8 in your code,  and (original - compressed) * * 2 will cause numerical overflow.

**Comment by Yongssss** [comment]
Please update your results in the paper.

**Comment by Wangt-CN** [comment]
Could you please check the formal implementatoin here: https://github.com/bonlime/pytorch-tools/blob/master/pytorch_tools/metrics/psnr.py#L11
The input range is [0,255]

**Comment by Yongssss** [comment]
> Could you please check the formal implementatoin here: https://github.com/bonlime/pytorch-tools/blob/master/pytorch_tools/metrics/psnr.py#L11 The input range is [0,255]

![image](https://github.com/Wangt-CN/DisCo/assets/48432038/e842856a-415e-4fb1-8384-09b276666d94)

The author claims in the issues that they have not used and even tested PSNR and SSIM.

**Comment by Yongssss** [comment]
https://github.com/bonlime/pytorch-tools/blob/01f40fe75c2a11683c247d8fcf3d3645a5783441/tests/metrics/test_metric.py#L105
![image](https://github.com/Wangt-CN/DisCo/assets/48432038/c853c41b-63bc-4f9a-912a-c43b5123d7a8)
And their images are float, but in your codes images are unit8.
